version: "3"

services:
  db:
    image: mongo
  front:
    image: node
    working_dir: /usr/app
    volumes:
      - ./front/:/usr/app
    ports:
      - "8888:4200"
    command: "npm start"
    depends_on:
      - db
  back:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./back:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
