version: "3"

services:
  db:
    image: mongo
    ports:
      - "27017:27017"
  front:
    image: node
    working_dir: /usr/app
    volumes:
      - ./djangoWeek_front:/usr/app
    ports:
      - "8888:4200"
    command: "npm start"
    depends_on:
      - db
  back:
    build: .
    command: bash -c "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./djangoWeek_back:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
