# Generated by Django 2.2.5 on 2019-09-12 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('idChannel', models.CharField(max_length=100)),
                ('idUser', models.CharField(max_length=100)),
                ('comment', models.TextField(blank=True, default='')),
            ],
        ),
    ]
