# Generated by Django 2.2.5 on 2019-09-12 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userMessage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermessage',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='usermessage',
            name='title',
        ),
    ]
